/*
 *******************************************************************************
 * Copyright (c) 2020-2026, STMicroelectronics
 * All rights reserved.
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 *******************************************************************************
 */
/*
 * Automatically generated from STM32C591V(E-G)Tx_pinout.json
 */
#if !defined(CUSTOM_PERIPHERAL_PINS)
#include "Arduino.h"
#include "PeripheralPins.h"

/* =====
 * Notes:
 * - The pins mentioned Px_y_ALTz are alternative possibilities which use other
 *   HW peripheral instances. You can use them the same way as any other "normal"
 *   pin (i.e. analogWrite(PA7_ALT1, 128);).
 *
 * - Commented lines are alternative possibilities which are not used per default.
 *   If you change them, you will have to know what you do
 * =====
 */

//*** ADC ***

#if defined(USE_HAL_ADC_MODULE) && (USE_HAL_ADC_MODULE == 1U)
WEAK const PinMap PinMap_ADC[] = {
  {PA_0,      ADC1, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 0, 0)}, // ADC1_IN0
  {PA_0_ALT1, ADC2, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 0, 0)}, // ADC2_IN0
  {PA_1,      ADC1, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 1, 0)}, // ADC1_IN1
  {PA_1_ALT1, ADC2, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 1, 0)}, // ADC2_IN1
  {PA_2,      ADC1, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 2, 0)}, // ADC1_IN2
  {PA_2_ALT1, ADC2, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 2, 0)}, // ADC2_IN2
  {PA_3,      ADC1, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 3, 0)}, // ADC1_IN3
  {PA_3_ALT1, ADC2, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 3, 0)}, // ADC2_IN3
  {PA_4,      ADC1, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 4, 0)}, // ADC1_IN4
  {PA_5,      ADC1, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 5, 0)}, // ADC1_IN5
  {PA_6,      ADC1, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 6, 0)}, // ADC1_IN6
  {PA_7,      ADC1, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 7, 0)}, // ADC1_IN7
  {PB_0,      ADC2, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 6, 0)}, // ADC2_IN6
  {PB_0_ALT1, ADC3, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 0, 0)}, // ADC3_IN0
  {PB_1,      ADC2, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 7, 0)}, // ADC2_IN7
  {PB_1_ALT1, ADC3, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 1, 0)}, // ADC3_IN1
  {PB_2,      ADC2, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 8, 0)}, // ADC2_IN8
  {PB_2_ALT1, ADC3, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 2, 0)}, // ADC3_IN2
  {PC_0,      ADC1, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 8, 0)}, // ADC1_IN8
  {PC_1,      ADC1, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 9, 0)}, // ADC1_IN9
  {PC_1_ALT1, ADC2, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 9, 0)}, // ADC2_IN9
  {PC_2,      ADC1, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 10, 0)}, // ADC1_IN10
  {PC_2_ALT1, ADC2, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 10, 0)}, // ADC2_IN10
  {PC_3,      ADC1, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 11, 0)}, // ADC1_IN11
  {PC_3_ALT1, ADC2, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 11, 0)}, // ADC2_IN11
  {PC_4,      ADC2, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 4, 0)}, // ADC2_IN4
  {PC_5,      ADC2, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 5, 0)}, // ADC2_IN5
  {PE_7,      ADC3, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 3, 0)}, // ADC3_IN3
  {PE_8,      ADC3, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 4, 0)}, // ADC3_IN4
  {PE_9,      ADC3, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 5, 0)}, // ADC3_IN5
  {PE_10,     ADC3, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 6, 0)}, // ADC3_IN6
  {PE_11,     ADC3, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 7, 0)}, // ADC3_IN7
  {PE_12,     ADC3, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 8, 0)}, // ADC3_IN8
  {PE_13,     ADC3, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 9, 0)}, // ADC3_IN9
  {PE_14,     ADC3, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 10, 0)}, // ADC3_IN10
  {PE_15,     ADC3, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 11, 0)}, // ADC3_IN11
  {PH_4,      ADC2, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 12, 0)}, // ADC2_IN12
  {PH_4_ALT1, ADC3, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 12, 0)}, // ADC3_IN12
  {PH_5,      ADC2, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 13, 0)}, // ADC2_IN13
  {PH_5_ALT1, ADC3, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 13, 0)}, // ADC3_IN13
  {NC,        NP,   0}
};
#endif

//*** DAC ***

#if defined(USE_HAL_DAC_MODULE) && (USE_HAL_DAC_MODULE == 1U)
WEAK const PinMap PinMap_DAC[] = {
  {PA_4, DAC1, STM_PIN_DATA_EXT(STM_MODE_ANALOG, LL_GPIO_PULL_NO, 0, 1, 0)}, // DAC1_OUT1
  {NC,   NP,  0}
};
#endif

//*** I2C ***

#if defined(USE_HAL_I2C_MODULE) && (USE_HAL_I2C_MODULE == 1U)
WEAK const PinMap PinMap_I2C_SDA[] = {
  {PA_12, I2C2, STM_PIN_DATA(STM_MODE_AF_OD, LL_GPIO_PULL_NO, HAL_GPIO_AF_8)},
  {PB_3,  I2C2, STM_PIN_DATA(STM_MODE_AF_OD, LL_GPIO_PULL_NO, HAL_GPIO_AF_4)},
  {PB_4,  I2C2, STM_PIN_DATA(STM_MODE_AF_OD, LL_GPIO_PULL_NO, HAL_GPIO_AF_9)},
  {PB_7,  I2C1, STM_PIN_DATA(STM_MODE_AF_OD, LL_GPIO_PULL_NO, HAL_GPIO_AF_4)},
  {PB_9,  I2C1, STM_PIN_DATA(STM_MODE_AF_OD, LL_GPIO_PULL_NO, HAL_GPIO_AF_4)},
  {PB_12, I2C2, STM_PIN_DATA(STM_MODE_AF_OD, LL_GPIO_PULL_NO, HAL_GPIO_AF_4)},
  {PC_9,  I2C1, STM_PIN_DATA(STM_MODE_AF_OD, LL_GPIO_PULL_NO, HAL_GPIO_AF_9)},
  {PH_0,  I2C1, STM_PIN_DATA(STM_MODE_AF_OD, LL_GPIO_PULL_NO, HAL_GPIO_AF_4)},
  {NC,    NP,   0}
};
#endif

#if defined(USE_HAL_I2C_MODULE) && (USE_HAL_I2C_MODULE == 1U)
WEAK const PinMap PinMap_I2C_SCL[] = {
  {PA_8,  I2C1, STM_PIN_DATA(STM_MODE_AF_OD, LL_GPIO_PULL_NO, HAL_GPIO_AF_9)},
  {PA_11, I2C2, STM_PIN_DATA(STM_MODE_AF_OD, LL_GPIO_PULL_NO, HAL_GPIO_AF_8)},
  {PB_3,  I2C2, STM_PIN_DATA(STM_MODE_AF_OD, LL_GPIO_PULL_NO, HAL_GPIO_AF_9)},
  {PB_6,  I2C1, STM_PIN_DATA(STM_MODE_AF_OD, LL_GPIO_PULL_NO, HAL_GPIO_AF_4)},
  {PB_8,  I2C1, STM_PIN_DATA(STM_MODE_AF_OD, LL_GPIO_PULL_NO, HAL_GPIO_AF_4)},
  {PB_10, I2C2, STM_PIN_DATA(STM_MODE_AF_OD, LL_GPIO_PULL_NO, HAL_GPIO_AF_4)},
  {PH_1,  I2C1, STM_PIN_DATA(STM_MODE_AF_OD, LL_GPIO_PULL_NO, HAL_GPIO_AF_4)},
  {NC,    NP,   0}
};
#endif

//*** I3C ***

#if defined(USE_HAL_I3C_MODULE) && (USE_HAL_I3C_MODULE == 1U)
WEAK const PinMap PinMap_I3C_SDA[] = {
  {PA_8,  I3C1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_NO, HAL_GPIO_AF_2)},
  {PB_5,  I3C1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_NO, HAL_GPIO_AF_3)},
  {PB_7,  I3C1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_NO, HAL_GPIO_AF_3)},
  {PB_9,  I3C1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_NO, HAL_GPIO_AF_3)},
  {PC_11, I3C1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_NO, HAL_GPIO_AF_4)},
  {PD_13, I3C1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_NO, HAL_GPIO_AF_5)},
  {NC,    NP,   0}
};
#endif

#if defined(USE_HAL_I3C_MODULE) && (USE_HAL_I3C_MODULE == 1U)
WEAK const PinMap PinMap_I3C_SCL[] = {
  {PA_9,  I3C1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_NO, HAL_GPIO_AF_2)},
  {PB_4,  I3C1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_NO, HAL_GPIO_AF_3)},
  {PB_6,  I3C1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_NO, HAL_GPIO_AF_3)},
  {PB_8,  I3C1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_NO, HAL_GPIO_AF_3)},
  {PC_10, I3C1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_NO, HAL_GPIO_AF_4)},
  {PD_12, I3C1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_NO, HAL_GPIO_AF_5)},
  {NC,    NP,   0}
};
#endif

//*** TIM ***

#if defined(USE_HAL_TIM_MODULE) && (USE_HAL_TIM_MODULE == 1U)
WEAK const PinMap PinMap_TIM[] = {
  {PA_0,       TIM2,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_1, 1, 0)}, // TIM2_CH1
  {PA_0_ALT1,  TIM5,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_2, 1, 0)}, // TIM5_CH1
  {PA_1,       TIM2,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_1, 2, 0)}, // TIM2_CH2
  {PA_1_ALT1,  TIM5,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_2, 2, 0)}, // TIM5_CH2
  {PA_1_ALT2,  TIM15, STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_4, 1, 1)}, // TIM15_CH1N
  {PA_2,       TIM2,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_1, 3, 0)}, // TIM2_CH3
  {PA_2_ALT1,  TIM5,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_2, 3, 0)}, // TIM5_CH3
  {PA_2_ALT2,  TIM15, STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_4, 1, 0)}, // TIM15_CH1
  {PA_3,       TIM2,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_1, 4, 0)}, // TIM2_CH4
  {PA_3_ALT1,  TIM3,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_2, 3, 0)}, // TIM3_CH3
  {PA_3_ALT2,  TIM5,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_8, 4, 0)}, // TIM5_CH4
  {PA_3_ALT3,  TIM15, STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_4, 2, 0)}, // TIM15_CH2
  {PA_4,       TIM3,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_2, 4, 0)}, // TIM3_CH4
  {PA_5,       TIM1,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_2, 3, 0)}, // TIM1_CH3
  {PA_5_ALT1,  TIM2,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_1, 1, 0)}, // TIM2_CH1
  {PA_5_ALT2,  TIM8,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_3, 1, 1)}, // TIM8_CH1N
  {PA_6,       TIM3,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_2, 1, 0)}, // TIM3_CH1
  {PA_7,       TIM1,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_1, 1, 1)}, // TIM1_CH1N
  {PA_7_ALT1,  TIM3,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_2, 2, 0)}, // TIM3_CH2
  {PA_7_ALT2,  TIM8,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_3, 1, 1)}, // TIM8_CH1N
  {PA_7_ALT3,  TIM15, STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_4, 1, 0)}, // TIM15_CH1
  {PA_8,       TIM1,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_1, 1, 0)}, // TIM1_CH1
  {PA_8_ALT1,  TIM2,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_14, 4, 0)}, // TIM2_CH4
  {PA_8_ALT2,  TIM5,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_8, 4, 0)}, // TIM5_CH4
  {PA_8_ALT3,  TIM15, STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_4, 2, 0)}, // TIM15_CH2
  {PA_9,       TIM1,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_1, 2, 0)}, // TIM1_CH2
  {PA_9_ALT1,  TIM8,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_13, 2, 1)}, // TIM8_CH2N
  {PA_9_ALT2,  TIM15, STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_4, 1, 1)}, // TIM15_CH1N
  {PA_10,      TIM1,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_1, 3, 0)}, // TIM1_CH3
  {PA_11,      TIM1,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_1, 4, 0)}, // TIM1_CH4
  {PA_15,      TIM1,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_2, 2, 1)}, // TIM1_CH2N
  {PA_15_ALT1, TIM2,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_1, 1, 0)}, // TIM2_CH1
  {PA_15_ALT2, TIM8,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_13, 4, 1)}, // TIM8_CH4N
  {PB_0,       TIM1,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_1, 2, 1)}, // TIM1_CH2N
  {PB_0_ALT1,  TIM3,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_2, 3, 0)}, // TIM3_CH3
  {PB_0_ALT2,  TIM8,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_3, 2, 1)}, // TIM8_CH2N
  {PB_1,       TIM1,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_1, 3, 1)}, // TIM1_CH3N
  {PB_1_ALT1,  TIM3,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_2, 4, 0)}, // TIM3_CH4
  {PB_1_ALT2,  TIM8,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_3, 3, 1)}, // TIM8_CH3N
  {PB_2,       TIM8,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_3, 4, 1)}, // TIM8_CH4N
  {PB_3,       TIM2,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_1, 2, 0)}, // TIM2_CH2
  {PB_3_ALT1,  TIM5,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_3, 3, 0)}, // TIM5_CH3
  {PB_3_ALT2,  TIM8,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_13, 1, 0)}, // TIM8_CH1
  {PB_4,       TIM3,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_2, 1, 0)}, // TIM3_CH1
  {PB_4_ALT1,  TIM8,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_13, 2, 0)}, // TIM8_CH2
  {PB_5,       TIM3,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_2, 2, 0)}, // TIM3_CH2
  {PB_5_ALT1,  TIM8,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_13, 3, 0)}, // TIM8_CH3
  {PB_6,       TIM4,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_2, 1, 0)}, // TIM4_CH1
  {PB_6_ALT1,  TIM8,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_13, 4, 0)}, // TIM8_CH4
  {PB_6_ALT2,  TIM16, STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_10, 1, 1)}, // TIM16_CH1N
  {PB_7,       TIM4,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_2, 2, 0)}, // TIM4_CH2
  {PB_7_ALT1,  TIM16, STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_10, 1, 0)}, // TIM16_CH1
  {PB_7_ALT2,  TIM17, STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_1, 1, 1)}, // TIM17_CH1N
  {PB_8,       TIM4,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_2, 3, 0)}, // TIM4_CH3
  {PB_8_ALT1,  TIM17, STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_1, 1, 0)}, // TIM17_CH1
  {PB_9,       TIM4,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_2, 4, 0)}, // TIM4_CH4
  {PB_10,      TIM2,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_1, 3, 0)}, // TIM2_CH3
  {PB_10_ALT1, TIM8,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_2, 1, 0)}, // TIM8_CH1
  {PB_12,      TIM8,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_2, 3, 0)}, // TIM8_CH3
  {PB_13,      TIM1,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_1, 1, 1)}, // TIM1_CH1N
  {PB_13_ALT1, TIM8,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_2, 2, 0)}, // TIM8_CH2
  {PB_14,      TIM1,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_1, 2, 1)}, // TIM1_CH2N
  {PB_14_ALT1, TIM8,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_3, 2, 1)}, // TIM8_CH2N
  {PB_14_ALT2, TIM12, STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_2, 1, 0)}, // TIM12_CH1
  {PB_15,      TIM1,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_1, 3, 1)}, // TIM1_CH3N
  {PB_15_ALT1, TIM8,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_3, 3, 1)}, // TIM8_CH3N
  {PB_15_ALT2, TIM12, STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_2, 2, 0)}, // TIM12_CH2
  {PC_2,       TIM4,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_2, 4, 0)}, // TIM4_CH4
  {PC_2_ALT1,  TIM17, STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_1, 1, 0)}, // TIM17_CH1
  {PC_4,       TIM2,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_1, 4, 0)}, // TIM2_CH4
  {PC_4_ALT1,  TIM16, STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_10, 1, 0)}, // TIM16_CH1
  {PC_5,       TIM1,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_1, 4, 1)}, // TIM1_CH4N
  {PC_5_ALT1,  TIM16, STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_10, 1, 1)}, // TIM16_CH1N
  {PC_6,       TIM3,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_2, 1, 0)}, // TIM3_CH1
  {PC_6_ALT1,  TIM8,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_3, 1, 0)}, // TIM8_CH1
  {PC_7,       TIM3,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_2, 2, 0)}, // TIM3_CH2
  {PC_7_ALT1,  TIM8,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_3, 2, 0)}, // TIM8_CH2
  {PC_8,       TIM3,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_2, 3, 0)}, // TIM3_CH3
  {PC_8_ALT1,  TIM8,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_3, 3, 0)}, // TIM8_CH3
  {PC_9,       TIM3,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_2, 4, 0)}, // TIM3_CH4
  {PC_9_ALT1,  TIM8,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_3, 4, 0)}, // TIM8_CH4
  {PC_10,      TIM8,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_3, 1, 1)}, // TIM8_CH1N
  {PC_11,      TIM8,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_3, 2, 1)}, // TIM8_CH2N
  {PC_12,      TIM8,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_3, 3, 1)}, // TIM8_CH3N
  {PC_12_ALT1, TIM15, STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_2, 1, 0)}, // TIM15_CH1
  {PC_14,      TIM12, STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_2, 1, 0)}, // TIM12_CH1
  {PC_15,      TIM12, STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_2, 2, 0)}, // TIM12_CH2
  {PD_0,       TIM8,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_3, 4, 1)}, // TIM8_CH4N
  {PD_5,       TIM1,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_1, 4, 1)}, // TIM1_CH4N
  {PD_12,      TIM4,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_2, 1, 0)}, // TIM4_CH1
  {PD_12_ALT1, TIM8,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_3, 1, 1)}, // TIM8_CH1N
  {PD_13,      TIM4,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_2, 2, 0)}, // TIM4_CH2
  {PD_13_ALT1, TIM8,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_3, 2, 1)}, // TIM8_CH2N
  {PD_14,      TIM4,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_2, 3, 0)}, // TIM4_CH3
  {PD_14_ALT1, TIM8,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_3, 3, 1)}, // TIM8_CH3N
  {PD_15,      TIM4,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_2, 4, 0)}, // TIM4_CH4
  {PD_15_ALT1, TIM8,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_3, 4, 1)}, // TIM8_CH4N
  {PE_4,       TIM15, STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_4, 1, 1)}, // TIM15_CH1N
  {PE_5,       TIM15, STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_4, 1, 0)}, // TIM15_CH1
  {PE_6,       TIM15, STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_4, 2, 0)}, // TIM15_CH2
  {PE_8,       TIM1,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_1, 1, 1)}, // TIM1_CH1N
  {PE_9,       TIM1,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_1, 1, 0)}, // TIM1_CH1
  {PE_10,      TIM1,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_1, 2, 1)}, // TIM1_CH2N
  {PE_11,      TIM1,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_1, 2, 0)}, // TIM1_CH2
  {PE_12,      TIM1,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_1, 3, 1)}, // TIM1_CH3N
  {PE_13,      TIM1,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_1, 3, 0)}, // TIM1_CH3
  {PE_14,      TIM1,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_1, 4, 0)}, // TIM1_CH4
  {PE_15,      TIM1,  STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_3, 4, 1)}, // TIM1_CH4N
  {PH_2,       TIM17, STM_PIN_DATA_EXT(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_1, 1, 1)}, // TIM17_CH1N
  {NC,         NP,    0}
};
#endif

//*** UART ***

#if defined(USE_HAL_UART_MODULE) && (USE_HAL_UART_MODULE == 1U)
WEAK const PinMap PinMap_UART_TX[] = {
  {PA_0,       UART4,   STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_8)},
  {PA_2,       USART2,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PA_3,       LPUART1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_3)},
  {PA_6,       USART1,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PA_9,       LPUART1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_3)},
  {PA_9_ALT1,  USART1,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PA_10,      UART7,   STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_10)},
  {PA_11,      USART2,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_4)},
  {PA_12,      UART4,   STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_6)},
  {PA_15,      USART1,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_11)},
  {PB_0,       USART2,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PB_3,       LPUART1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_8)},
  {PB_3_ALT1,  USART3,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_11)},
  {PB_6,       LPUART1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_8)},
  {PB_6_ALT1,  UART5,   STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_14)},
  {PB_6_ALT2,  USART1,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PB_9,       UART4,   STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_8)},
  {PB_10,      USART3,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PB_13,      UART5,   STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_14)},
  {PB_14,      USART1,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_4)},
  {PC_3,       LPUART1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_3)},
  {PC_6,       USART6,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PC_10,      UART4,   STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_8)},
  {PC_10_ALT1, USART3,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PC_12,      UART5,   STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_8)},
  {PD_1,       UART4,   STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_8)},
  {PD_5,       USART2,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PD_8,       USART3,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PD_12,      UART4,   STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_8)},
  {PE_4,       USART1,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PE_8,       UART7,   STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {NC,         NP,      0}
};
#endif

#if defined(USE_HAL_UART_MODULE) && (USE_HAL_UART_MODULE == 1U)
WEAK const PinMap PinMap_UART_RX[] = {
  {PA_1,       UART4,   STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_8)},
  {PA_2,       LPUART1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_3)},
  {PA_3,       USART2,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PA_7,       USART1,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PA_8,       UART7,   STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_10)},
  {PA_10,      LPUART1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_3)},
  {PA_10_ALT1, USART1,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PA_11,      UART4,   STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_6)},
  {PA_12,      USART2,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_4)},
  {PB_1,       USART3,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PB_4,       USART3,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_11)},
  {PB_5,       UART5,   STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_14)},
  {PB_7,       LPUART1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_8)},
  {PB_7_ALT1,  USART1,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PB_8,       UART4,   STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_8)},
  {PB_12,      UART5,   STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_14)},
  {PB_13,      LPUART1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_8)},
  {PB_15,      UART5,   STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_14)},
  {PB_15_ALT1, USART1,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_4)},
  {PC_4,       USART3,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PC_7,       USART6,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PC_11,      UART4,   STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_8)},
  {PC_11_ALT1, USART3,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PD_0,       UART4,   STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_8)},
  {PD_2,       UART5,   STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_8)},
  {PD_6,       USART2,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PD_9,       USART3,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PD_11,      UART4,   STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_8)},
  {PE_3,       USART1,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PE_7,       UART7,   STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {NC,         NP,      0}
};
#endif

#if defined(USE_HAL_UART_MODULE) && (USE_HAL_UART_MODULE == 1U)
WEAK const PinMap PinMap_UART_RTS[] = {
  {PA_1,       USART2,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PA_6,       LPUART1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_8)},
  {PA_12,      LPUART1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_3)},
  {PA_12_ALT1, USART1,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PA_15,      UART4,   STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_8)},
  {PB_3,       UART5,   STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_14)},
  {PB_5,       LPUART1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_8)},
  {PB_7,       USART3,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_11)},
  {PB_14,      UART4,   STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_8)},
  {PB_14_ALT1, USART3,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PC_8,       UART5,   STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_8)},
  {PD_4,       USART2,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PD_12,      USART3,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PE_9,       UART7,   STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PH_15,      USART1,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {NC,         NP,      0}
};
#endif

#if defined(USE_HAL_UART_MODULE) && (USE_HAL_UART_MODULE == 1U)
WEAK const PinMap PinMap_UART_CTS[] = {
  {PA_0,       USART2,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PA_5,       USART1,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PA_7,       LPUART1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_8)},
  {PA_11,      LPUART1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_3)},
  {PA_11_ALT1, USART1,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PB_0,       UART4,   STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_8)},
  {PB_4,       LPUART1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_8)},
  {PB_4_ALT1,  UART5,   STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_14)},
  {PB_6,       USART3,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_11)},
  {PB_13,      USART3,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PB_15,      UART4,   STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_8)},
  {PC_9,       UART5,   STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_8)},
  {PD_3,       USART2,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PD_11,      USART3,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PE_6,       USART1,  STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PE_10,      UART7,   STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {NC,         NP,      0}
};
#endif

//*** SPI ***

#if defined(USE_HAL_SPI_MODULE) && (USE_HAL_SPI_MODULE == 1U)
WEAK const PinMap PinMap_SPI_MOSI[] = {
  {PA_3,       SPI3, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_6)},
  {PA_4,       SPI3, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_4)},
  {PA_7,       SPI1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_5)},
  {PA_8,       SPI2, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_6)},
  {PB_2,       SPI3, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PB_5,       SPI1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_5)},
  {PB_5_ALT1,  SPI3, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PB_15,      SPI1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_6)},
  {PB_15_ALT1, SPI2, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_5)},
  {PB_15_ALT2, SPI3, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PC_1,       SPI2, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_5)},
  {PC_3,       SPI2, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_5)},
  {PC_12,      SPI3, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_6)},
  {PD_6,       SPI3, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_5)},
  {PD_7,       SPI1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_5)},
  {PE_6,       SPI3, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_5)},
  {NC,         NP,   0}
};
#endif

#if defined(USE_HAL_SPI_MODULE) && (USE_HAL_SPI_MODULE == 1U)
WEAK const PinMap PinMap_SPI_MISO[] = {
  {PA_6,      SPI1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_5)},
  {PA_7,      SPI2, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_6)},
  {PB_0,      SPI3, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_5)},
  {PB_4,      SPI1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_5)},
  {PB_4_ALT1, SPI3, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_6)},
  {PB_6,      SPI3, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_6)},
  {PB_14,     SPI2, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_5)},
  {PC_2,      SPI2, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_5)},
  {PC_11,     SPI3, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_6)},
  {PD_7,      SPI3, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_6)},
  {PE_5,      SPI3, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_5)},
  {NC,        NP,   0}
};
#endif

#if defined(USE_HAL_SPI_MODULE) && (USE_HAL_SPI_MODULE == 1U)
WEAK const PinMap PinMap_SPI_SCLK[] = {
  {PA_5,      SPI1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_5)},
  {PA_5_ALT1, SPI2, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_6)},
  {PA_9,      SPI2, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_5)},
  {PA_12,     SPI2, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_5)},
  {PB_1,      SPI3, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_4)},
  {PB_2,      SPI2, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_6)},
  {PB_3,      SPI1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_5)},
  {PB_3_ALT1, SPI3, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_6)},
  {PB_7,      SPI3, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_6)},
  {PB_9,      SPI3, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_6)},
  {PB_10,     SPI2, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_5)},
  {PB_13,     SPI2, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_5)},
  {PC_10,     SPI3, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_6)},
  {PD_3,      SPI2, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_5)},
  {PE_2,      SPI3, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_5)},
  {NC,        NP,   0}
};
#endif

#if defined(USE_HAL_SPI_MODULE) && (USE_HAL_SPI_MODULE == 1U)
WEAK const PinMap PinMap_SPI_SSEL[] = {
  {PA_0,       SPI2, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_9)},
  {PA_3,       SPI2, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_5)},
  {PA_4,       SPI1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_5)},
  {PA_4_ALT1,  SPI3, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_6)},
  {PA_11,      SPI2, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_5)},
  {PA_15,      SPI1, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_5)},
  {PA_15_ALT1, SPI3, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_6)},
  {PB_1,       SPI2, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_5)},
  {PB_4,       SPI2, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_7)},
  {PB_8,       SPI3, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_6)},
  {PB_9,       SPI2, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_5)},
  {PB_12,      SPI2, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_5)},
  {PE_4,       SPI3, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_5)},
  {NC,         NP,   0}
};
#endif

//*** No CAN ***

//*** No ETHERNET ***

//*** No QUADSPI ***

//*** USB ***

#if defined(USE_HAL_PCD_MODULE) && (USE_HAL_PCD_MODULE == 1U) ||\
    defined(USE_HAL_HCD_MODULE) && (USE_HAL_HCD_MODULE == 1U)
WEAK const PinMap PinMap_USB[] = {
  {PA_8,  USB, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_UP, HAL_GPIO_AF_13)}, // USB_SOF
  {PA_11, USB, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_NO, HAL_GPIO_AF_7)}, // USB_DM
  {PA_12, USB, STM_PIN_DATA(STM_MODE_AF_PP, LL_GPIO_PULL_NO, HAL_GPIO_AF_7)}, // USB_DP
  {NC,    NP,  0}
};
#endif

//*** No SD ***

#endif /* !CUSTOM_PERIPHERAL_PINS */
